name: slimsocial_for_facebook
description: Webview to securely navigate Facebook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 25.04.06+116

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_jailbreak_detection:
    git:
      url: https://github.com/pdurasie-ecovery/flutter_jailbreak_detection.git
      ref: add-namespace
  webview_flutter: 4.10.0
  flutter_custom_tabs: 2.2.1
  url_launcher: 6.3.1
  permission_handler: 11.4.0
  shared_preferences: 2.5.3
  app_links: 6.4.0
  settings_ui: 2.0.2
  flutter_riverpod: 2.6.1
  in_app_purchase: 3.2.1
  fluttertoast: 8.2.12
  easy_localization: 3.0.7
  package_info_plus: 8.3.0
  restart_app: 1.3.2
  google_fonts: 6.2.1
  in_app_review: 2.0.10
  share_plus: 10.1.4
  file_picker: 10.0.0
  flutter_file_downloader: 2.1.0
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
  native_flutter_proxy: 0.2.3

  webview_flutter_android: any
dev_dependencies:
  flutter_launcher_icons: 0.14.3
  custom_lint: 0.7.5
  very_good_analysis: 7.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lang/
